### ISSUE TITLE
Utilities build is broken

### ISSUE THREAD

**Issue by rgerganov** [vmware-research/certifier-framework-for-confidential-computing#58]
I am getting a compilation error when trying the build the utilities:
```
➜  utilities git:(main) make -f cert_utility.mak    
protoc -I../src --cpp_out=. ../src/certifier.proto
mv certifier.pb.h ../include
compiling cert_utility.cc
g++ -I../include -I/usr/local/opt/openssl@1.1/include/ -I../src/sev-snp/ -O3 -g -Werror -Wall -std=c++11 -Wno-unused-variable -D X64 -Wno-deprecated -Wno-deprecated-declarations -c -o ./cert_utility.o ./cert_utility.cc
compiling certifier.pb.cc
g++ -I../include -I/usr/local/opt/openssl@1.1/include/ -I../src/sev-snp/ -O3 -g -Werror -Wall -std=c++11 -Wno-unused-variable -D X64 -Wno-deprecated -Wno-deprecated-declarations -c  -o ./certifier.pb.o ./certifier.pb.cc
In file included from /usr/include/string.h:495,
                 from /usr/include/google/protobuf/stubs/port.h:38,
                 from /usr/include/google/protobuf/stubs/common.h:46,
                 from ../include/certifier.pb.h:9,
                 from ./certifier.pb.cc:4:
In function ‘void* memset(void*, int, size_t)’,
    inlined from ‘void time_point::SharedCtor()’ at ./certifier.pb.cc:1753:11,
    inlined from ‘time_point::time_point()’ at ./certifier.pb.cc:1738:13,
    inlined from ‘void protobuf_certifier_2eproto::InitDefaultstime_point()’ at ./certifier.pb.cc:1734:1:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:71:33: error: ‘void* __builtin_memset(void*, int, long unsigned int)’ offset [29, 52] from the object at ‘_time_point_default_instance_’ is out of the bounds of referenced subobject ‘time_point::year_’ with type ‘int’ at offset 24 [-Werror=array-bounds]
   71 |   return __builtin___memset_chk (__dest, __ch, __len, __bos0 (__dest));
      |          ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
...
```
This is a regression introduced with commit c7963d9e5f608 which adds `-Werror` to utilities makefiles.
I am not sure why compiling the generated protobuf file generates a warning but if we treat warnings as errors here, the build fails.

/cc @gapisback

**Comment by gapisback** [comment]
@rgerganov - I am assuming that this is failing on SGX platform, for some app other than `simple_app`, right

I have fixed this while extending `run_example.sh` to also run for simple_app_under_oe app program.

Do you need the 'fix' (to avoid `-Werror` for protobuf-generated files) to come-in to `/main` on its own, before waiting for fix for issue #67 to be finalized and reviewed? If yes, I can do a patch-fix for just this regression on its own.
